---
- name: create temporary file
  ansible.builtin.tempfile:
    state: file
    suffix: temp
  register: my_tempfile

- name: add content to file
  ansible.builtin.copy:
    dest: "{{ my_tempfile.path }}"
    content: "{{ ls_file_content }}"

- name: copy file on log server
  ansible.builtin.command: "kubectl cp -n {{ namespace }} {{ my_tempfile.path }} logserver-0:/var/www/html/logs/{{ ls_file_name }}"

- name: destroy temporary file
  ansible.builtin.file:
    path: "{{ my_tempfile.path }}"
    state: absent
