---
- name: "Ensure removal of {{ output_dir }}"
  ansible.builtin.file:
    path: "{{ output_dir }}"
    state: absent

- name: Start port forwarding to git server
  ansible.builtin.shell: |
    kubectl port-forward service/git-server 9418 -n sf
  async: 60
  poll: 0
  ignore_errors: true

- name: Clone system-config
  ansible.builtin.git:
    repo: git://localhost:9418/system-config
    dest: "{{ output_dir }}"
  register: clone
  retries: "{{ retries }}"
  delay: "{{ delay }}"
  until: "clone is not failed"
  ignore_errors: true
