---
- name: Install dependencies
  become: true
  when: install_requirements
  block:
    - name: Install go
      ansible.builtin.include_role: name=install-golang

    - name: Install packages
      ansible.builtin.package:
        name:
          - jq
          - make
          - podman
          - buildah
          - skopeo
          - openssl
          - python3-cryptography
          - zip
          - unzip
          - python3-pip
          - python3-setuptools
          - gcc

    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - git-review
          - kubernetes
          - oauthlib>=3.2.2
          - websocket-client
