apiVersion: sf.softwarefactory-project.io/v1
kind: SoftwareFactory
metadata:
  name: my-sf
spec:
  fqdn: "sfop.me"
  config-location:
    name: config
    zuul-connection-name: gerrit
  zuul:
    gerritconns:
      - name: gerrit
        username: zuul
        hostname: gerrit-sshd.sf
        puburl: "https://gerrit.sfop.me"
        verifyssl: false
    executor:
      logLevel: DEBUG
  logserver:
    loopDelay: 3600
    retentionDays: 30
    storage:
      size: 2Gi
