- project:
    check:
      jobs:
        - sf-operator-minikube-integration
        - sf-operator-minikube-upgrade
        - sf-operator-microshift-integration
        - sf-operator-microshift-upgrade
        - sf-operator-vuln-check
        - sf-operator-ansible-lint
        - sf-operator-go-test
        - sf-operator-doc-check
    gate:
      fail-fast: true
      jobs:
        - sf-operator-minikube-integration
        - sf-operator-minikube-upgrade
        - sf-operator-microshift-integration
        - sf-operator-microshift-upgrade
        - sf-operator-vuln-check
        - sf-operator-ansible-lint
        - sf-operator-go-test
        - sf-operator-doc-check
    periodic:
      jobs:
        - sf-operator-minikube
        - sf-operator-microshift-integration
        - sf-operator-microshift-upgrade
