- hosts: "{{ hostname | default('controller') }}"
  tasks:
    - name: "Grab minikube logs"
      shell: |
        mkdir -p ~/zuul-output/logs/
        minikube logs > ~/zuul-output/logs/minikube.logs
        sudo dmesg > ~/zuul-output/logs/dmesg.txt

    # Fetch k8s resources for the sf namespace
    - ansible.builtin.include_role:
        name: post/get-kubectl-logs
      vars:
        namespace: sf

    - ansible.builtin.include_role:
          name: post/get-logserver-content

    # Fetch repos stored on code review service
    - ansible.builtin.include_role:
          name: post/get-repos
