---
- hosts: "{{ hostname | default('controller') }}"
  vars:
    kubectl: "minikube kubectl -- "
  tasks:
    - name: Crete sf namespace
      ansible.builtin.command:
        cmd: "{{ kubectl }} create ns sf"

    - name: Set sf as the default namespace
      ansible.builtin.command:
        cmd: "{{ kubectl }} config set-context --current --namespace sf"
