---
- hosts: "{{ hostname | default('controller') }}"
  vars:
    mode: standalone
  vars:
    project_dir: "{% if zuul.project.src_dir is defined %}~/{{ zuul.project.src_dir }}{% else %}..{% endif %}"
  pre_tasks:
    - name: Grab load balancer IP
      command: awk '/ gerrit./ { print $1 }' /etc/hosts
      register: _etc_host_ip
    - name: Set hostAliases - edit playbooks/files/ yaml files
      ansible.builtin.include_role:
        name: create-hostaliases-cr
      vars:
        iplb_ip_address: "{{ _etc_host_ip.stdout }}"
      loop:
        - "{{ project_dir }}/playbooks/files/ext-ze.yaml"
        - "{{ project_dir }}/playbooks/files/sf.yaml"
        - "{{ project_dir }}/playbooks/files/sf-operator-cli.yaml"
      loop_control:
        loop_var: yaml_file

    - name: Install test dependencies
      become: true
      ansible.builtin.package:
        name:
          - unzip
  roles:
    - setup-variables
    - setup-nodepool-ns
    - utils/get-gerrit-admin-user-api-key
    - utils/config-repo-reset
    - utils/setup-log-forwarding-stack

    # Apply the sf.yaml resources with the config repo on gerrit
    - run-operator-standalone

    # Validate services are working
    - health-check/check-service-uri
    - health-check/check-zuul-weeder
    - health-check/enable-log-forward
    - health-check/scale-resources
    - health-check/zuul-connections
    - health-check/zuul-authenticators

    # FIXME: add more health-check
    # - health-check/config-update-zuul
    # - health-check/check-logjuicer
    # - health-check/zuul-demo-tenant-workflow
    # - health-check/test-nodepool-providers-secrets
    # - health-check/config-update-nodepool-launcher
    # - health-check/config-update-nodepool-builder
    # - health-check/test-nodepool-launcher-pod
    # - health-check/test-volumestats-sidecar
