---
- hosts: "{{ hostname | default('controller') }}"
  vars:
    mode: standalone
  vars:
    project_dir: "{% if zuul.project.src_dir is defined %}~/{{ zuul.project.src_dir }}{% else %}..{% endif %}"
  pre_tasks:
    - name: Install test dependencies
      become: true
      ansible.builtin.package:
        name:
          - unzip
  roles:
    - setup-variables
    - setup-nodepool-ns
    - utils/get-gerrit-admin-user-api-key
    - utils/config-repo-reset
    - utils/setup-log-forwarding-stack

    # Apply the sf.yaml resources with the config repo on gerrit
    - run-operator-standalone

    # Validate services are working
    - health-check/check-service-uri
    - health-check/check-zuul-weeder
    - health-check/enable-log-forward
    - health-check/scale-resources
    - health-check/zuul-connections
    - health-check/zuul-authenticators
    - health-check/config-update-zuul
    - health-check/check-logjuicer
    - health-check/zuul-demo-tenant-workflow
    - health-check/zuul-executor-ensure-graceful-stop
    - health-check/test-nodepool-providers-secrets
    - health-check/config-update-nodepool-launcher
    - health-check/test-nodeAffinity
    - health-check/test-deploy-zero-replica

    # FIXME: add more health-check
    # - health-check/config-update-nodepool-builder
    # - health-check/test-nodepool-launcher-pod
    # - health-check/test-volumestats-sidecar

  tasks:
    # test versioning
    - name: Register CLI version
      register: cli_version
      ansible.builtin.shell: |
        set -o pipefail
        go run main.go version
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: ensure annotations are present on sf-standalone-owner
      ansible.builtin.shell: "kubectl -n sf get configmap sf-standalone-owner -o jsonpath='{.metadata.annotations}'"
      register: cm_annotations
      failed_when:
        - "'last_reconciled' not in cm_annotations.stdout"
        - "'version' not in cm_annotations.stdout"
        - "cli_version.stdout not in cm_annotations.stdout"
